// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hygkdflkvhxaxcawxibe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5Z2tkZmxrdmh4YXhjYXd4aWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjg4MTMsImV4cCI6MjA3MjY0NDgxM30.49Pqhdz8AKliDtF-75OXe6V_17tij8yEg0oMw4pmCWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});